"""Init

Revision ID: 7ddd42043012
Revises: 
Create Date: 2026-04-13 16:55:13.214125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7ddd42043012'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('second_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('full_name IS NULL OR length(full_name) <= 50', name='full_name_length'),
    sa.CheckConstraint('length(password) >= 5 AND length(password) <= 250', name='password_length'),
    sa.CheckConstraint('length(username) >= 3 AND length(username) <= 50', name='username_length'),
    sa.CheckConstraint('second_name IS NULL OR length(second_name) <= 50', name='second_name_length'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('book',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('description IS NULL OR length(description) <= 50', name='description_length'),
    sa.CheckConstraint('length(author) >= 5 AND length(author) <= 50', name='author_length'),
    sa.CheckConstraint('length(title) >= 3 AND length(title) <= 50', name='title_length'),
    sa.CheckConstraint('price > 0 AND price < 50', name='price_gt_lt'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
